### PR TITLE
Use CDI to instantiate Application classes to invoke getClasses

### LINKED ISSUE #2324: MPOpenAPIBuilder calls Application.getClasses() with unresolved Injection points
## Environment Details
* Helidon Version: 2.0.1
*  Helidon MP
* JDK version: 11

----------

## Problem Description

If an Application's `getClasses()` method relies on Injected fields, those fields can be null if OpenAPI support is enabled.

## Steps to reproduce

1. Get the reproducer from issue #2270 
2. Build using Java 11: `gradle clean build`
3. `export VAR=foo`
4. `java -jar build/libs/helidon-2-possible-cdi-issue.jar `

You should get a NPE like:

```
2020-09-03 12:38:31,509 [INFO] [:No Correlation ID] org.jboss.weld.Bootstrap Thread[main]: WELD-ENV-002001: Weld SE container fb1ca7ff-1d37-44b3-91f6-c543cb058994 shut down
Exception in thread "main" java.lang.NullPointerException
        at dk.bankdata.drb.api.RestApplication.getClasses(RestApplication.java:25)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.classesToScanForApp(MPOpenAPIBuilder.java:131)
        at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:195)
        at java.base/java.util.stream.SortedOps$SizedRefSortingSink.end(SortedOps.java:357)
        at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:485)
        at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:474)
        at java.base/java.util.stream.ReduceOps$ReduceOp.evaluateSequential(ReduceOps.java:913)
        at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
        at java.base/java.util.stream.ReferencePipeline.collect(ReferencePipeline.java:578)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.buildPerAppFilteredIndexViews(MPOpenAPIBuilder.java:103)
        at io.helidon.microprofile.openapi.MPOpenAPIBuilder.perAppFilteredIndexViews(MPOpenAPIBuilder.java:59)
        at io.helidon.openapi.OpenAPISupport.<init>(OpenAPISupport.java:139)
        at io.helidon.openapi.OpenAPISupport$Builder.build(OpenAPISupport.java:648)
        at io.helidon.microprofile.openapi.OpenApiCdiExtension.registerOpenApi(OpenApiCdiExtension.java:111)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
        at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.base/java.lang.reflect.Method.invoke(Method.java:566)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:95)
        at org.jboss.weld.injection.StaticMethodInjectionPoint.invoke(StaticMethodInjectionPoint.java:85)
        at org.jboss.weld.injection.MethodInvocationStrategy$SimpleMethodInvocationStrategy.invoke(MethodInvocationStrategy.java:168)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:330)
        at org.jboss.weld.event.ExtensionObserverMethodImpl.sendEvent(ExtensionObserverMethodImpl.java:123)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:308)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:335)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:245)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

If you update the `build.gradle` to to have helidon dependencies like this:
```
    implementation enforcedPlatform("io.helidon:helidon-dependencies:${project['io.helidon.version']}")
    //implementation 'io.helidon.microprofile.bundles:helidon-microprofile'
    implementation 'io.helidon.microprofile.bundles:helidon-microprofile-core'
    implementation 'io.helidon.microprofile.tracing:helidon-microprofile-tracing'
    implementation 'io.helidon.microprofile.health:helidon-microprofile-health'
    implementation 'io.helidon.microprofile.metrics:helidon-microprofile-metrics'
    //implementation 'io.helidon.microprofile.openapi:helidon-microprofile-openapi'
    implementation 'io.helidon.tracing:helidon-tracing-jaeger'
```
The application starts up OK because the openapi support is not enabled.

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #2324 

Originally, the OpenAPI code instantiated `Application` classes directly so as to invoke their `getClasses` method. 

This does not work if the `Application` injects a bean _and_ uses the bean in the `getClasses` method.

This PR uses CDI's `Unmanaged` constructs to temporarily instantiate and inject each `Application` class, invoke `getClasses`, then dispose of the instance.

Thanks to @ljnelson for the idea of the solution.

### CODE REVIEW

File: microprofile/openapi/src/main/java/io/helidon/microprofile/openapi/MPOpenAPIBuilder.java [hunk 1]
```diff
@@ -172,14 +172,11 @@ MPOpenAPIBuilder config(Config mpConfig) {
...
-            throw new RuntimeException(e);
-        } catch (NoSuchMethodException e) {
-            // Wrapper app does not have a no-args constructor so we canont instantiate it.
-            return Optional.empty();
-        }
+        Unmanaged<? extends Application> unmanagedApp = new Unmanaged<>(appClass);
+        Unmanaged.UnmanagedInstance<? extends Application> unmanagedInstance = unmanagedApp.newInstance();
+        Application app = unmanagedInstance.produce().inject().postConstruct().get();
+        unmanagedInstance.preDestroy().dispose();
+        return Optional.of(app);
```
Comment (ljnelson) [inline microprofile/openapi/src/main/java/io/helidon/microprofile/openapi/MPOpenAPIBuilder.java:179]: Since disposal will do nothing, this is probably OK, but it looks weird.  I wonder if you can move this `Unmanaged` stuff elsewhere, like where you call something like `getClasses()` on the `Application` instance, and do the disposal afterwards.

Comment (tjquinno) [reply microprofile/openapi/src/main/java/io/helidon/microprofile/openapi/MPOpenAPIBuilder.java:179]: It sounds as if your concern is that the use of the instance (the `app`) outlives the `unmanagedInstance` that gave rise to it. 

I see how that does look a bit odd. But the app instance also outlives the code around line 123 and in fact is used not only in the same `MPOpenAPIBuilder` but also in a separate class `OpenApiCdiExtension.` 

I'll take a look at refactoring things to address that admittedly odd-looking code without altering too much the way the consuming code operates. Thanks for the catch.

Comment (ljnelson) [reply microprofile/openapi/src/main/java/io/helidon/microprofile/openapi/MPOpenAPIBuilder.java:179]: Yeah, the main problem is that dependent objects that may get injected into the `Application` instance (and of course it's user-supplied so you don't have any control over it) may get flushed/released/disposed when that `dispose()` call is made.  So you don't want them to go away obviously while the `Application` instance is in use somewhere.

Comment (tjquinno) [reply microprofile/openapi/src/main/java/io/helidon/microprofile/openapi/MPOpenAPIBuilder.java]: The latest push rearranges the code so it uses any unmanaged instance as much as needed, and only then disposes of it.

**Review by ljnelson — APPROVED** [review]
Very clean; LGTM
