### PR TITLE
Automated discovery of JAX-RS method entities.

### LINKED ISSUE #3090: Should automatically provide GraalVM settings when endpoint accepts or returns a POJO
## Environment Details
* Helidon Version: 2.3.0
* Helidon SE or Helidon MP MP
* JDK version: n/a
* OS: n/a
* Docker version (if applicable): n/a

----------

## Problem Description
A JAX-RS endpoint method which returns a POJO works fine when launched using `java -jar` but returns empty responses when run as a native image.

## Steps to reproduce
1. Use `helidon init` to create an MP project based on the quick-start example.
2. Add a POJO `Message` class with the `String` attribute `message`:
    ```
    public class Message {
        private String message;
    
        public Message(String msg) {
            message = msg;
        }
    
        public String getMessage() {
            return message;
        }

        public void setMessage(String message) {
            this.message = message;
        }
    }
    ```
3. Modify one of the generated endpoints, or add a new one at a new path, which instantiates and returns a `Message` object instead of `JsonObject`:
    ```
        @GET
        @Path("/pojo")
        @Produces(MediaType.APPLICATION_JSON)
        public Message getDefaultMessagePojo() {
            return new Message(String.format("%s %s!", greetingProvider.getMessage(), "World"));
        } 
    ```
4. Build for GraalVM but run _without_ GraalVM:
    ```
    mvn package -Pnative-image
    java -jar target/quickstart-mp.jar
    ```
    Access the endpoint: `curl http://localhost:8080/greet/pojo` The response is as expected.
5. Run _with_ GraalVM (`-Pnative-image`). Access the endpoint. The response is empty.

## To work around this:
1. Add 
    ```
    [
      {
        "name": "me.tjquinn.mp.quickstart.Message",
        "allPublicConstructors" : true,
        "allPublicMethods" : true
      }
    ]
    ```
    to the empty generated `META-INF/native-image/reflect-config.json` file.
2. Rebuild (with `-Pnative-image`) and rerun. The response is now correct.

## Change:
Ideally, Helidon would automatically generate the `reflect-config` data for any POJO that the developer uses as a JAX-RS endpoint parameter or return value.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #3090 

Added analysis of response types of JAX-RS resource methods, and entity parameter types (types with no annotation).
These types are added for reflection automatically now.

Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

### CODE REVIEW

File: integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java [hunk 1]
```diff
@@ -222,6 +225,17 @@ private void addJaxRsConversions(BeforeAnalysisContext context, String annotatio
         }
     }
 
+    private void processJaxRsTypes(BeforeAnalysisContext context) {
+        tracer.parsing(() -> "Looking up JAX-RS resource methods.");
+
+        new JaxRsMethodAnalyzer(context, util)
```
Comment (spericas) [inline integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java:231]: Looks a bit weird not being a static method or using a local var.

**Review by spericas — APPROVED** [review]

File: integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java (hunk 1 above)
Comment (tomas-langer) [reply integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java:231]: I have merged the PR even with this comment, as I do not think of it as a technical debt. The implementation was easier using an instance.
