### PR TITLE
Container startup issue fixed.

### LINKED ISSUE #1446: Container starts even if exception is thrown during initialization
# Helidon container starts even if exception is thrown during initialization

## Environment Details
* Helidon Version: master 2.0.0-SNAPSHOT
* Helidon MP
* JDK version: 11
* OS: Ubuntu

----------

## Problem Description
Helidon container starts even if exception is thrown during initialization(after deployment)

## Steps to reproduce
```java
void init(@Observes @Priority(PLATFORM_AFTER + 101) @Initialized(ApplicationScoped.class) Object e, BeanManager bm) {
   throw new RuntimeException("Survive this!");
}
```
## Reproducer

```java
@Test
    void testCleanDeath() {
        assertThrows(IllegalStateException.class, CDI::current);
        assertThrows(RuntimeException.class, () -> startCdiContainer(Map.of(), Set.of(TestBean.class)));
        assertThrows(IllegalStateException.class, CDI::current);
    }

    private static SeContainer startCdiContainer(Map<String, String> p, Set<Class<?>> beanClasses) {
        Config config = ConfigProviderResolver.instance().getBuilder()
                .withSources(MpConfigSources.create(p),
                        MpConfigSources.create(Map.of("mp.initializer.allow", "true")))
                .build();

        ConfigProviderResolver.instance()
                .registerConfig(config, Thread.currentThread().getContextClassLoader());

        final SeContainerInitializer initializer = SeContainerInitializer.newInstance();
        initializer.addBeanClasses(beanClasses.toArray(new Class<?>[0]));
        return initializer.initialize();
    }

    @ApplicationScoped
    static class TestBean {
        void init(@Observes @Priority(PLATFORM_AFTER + 101) @Initialized(ApplicationScoped.class) Object e, BeanManager bm) {
            throw new RuntimeException("Survive this!");
        }
    }
```

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

Resolves #1446

### CODE REVIEW

File: microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java [hunk 1]
```diff
@@ -216,6 +228,17 @@ private void registerClasspathStaticContent(Config config) {
     }
 
     private void stopServer(@Observes @Priority(PLATFORM_BEFORE) @BeforeDestroyed(ApplicationScoped.class) Object event) {
+        boolean isRunning = IN_PROGRESS_OR_RUNNING.get();
+        try {
+            doStop(event);
+        } finally {
+            if (isRunning) {
+                IN_PROGRESS_OR_RUNNING.set(false);
+            }
```
Comment (tjquinno) [inline microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java:237]: This logic sets `IN_PROGRESS_OR_RUNNING` to false only if it was true at the start of the method. Could there be a race condition here in which an (incorrect) second attempt to start the server concurrently occurred after `isRunning` is assigned `false` (and that parallel start-up would set `IN_PROGRESS_OR_RUNNING` to `true`), the `doStop` actually does the shutdown, but because `isRunning` is not true then `IN_PROGRESS_OR_RUNNING` is not set to `false`? So the server would be stopped but `IN_PROGRESS_OR_RUNNING` incorrectly says `true`. 

Maybe this cannot happen in practice because of other reasons?

Comment (tomas-langer) [reply microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java:237]: There was a problem with this. Fixing.

Comment (tomas-langer) [reply microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java]: Fixing this uncovered other issues with correct shutdown. Fixed them as well.
