### PR TITLE
ClassPathContentHandler can survive tmp folder cleanup

### LINKED ISSUE #2358: Cleared tmp folder breaks static content serving
```
[Mon Sep 14 16:16:34 GMT 2020] SEVERE: io.helidon.webserver.BareResponseImpl writeLastContent - (reqID: 411) Upstream error while sending response. 
java.nio.file.NoSuchFileException: /tmp/ws15313857226039390689.je
	at java.base/sun.nio.fs.UnixException.translateToIOException(UnixException.java:92)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:111)
	at java.base/sun.nio.fs.UnixException.rethrowAsIOException(UnixException.java:116)
	at java.base/sun.nio.fs.UnixFileAttributeViews$Basic.readAttributes(UnixFileAttributeViews.java:55)
	at java.base/sun.nio.fs.UnixFileSystemProvider.readAttributes(UnixFileSystemProvider.java:149)
	at java.base/sun.nio.fs.LinuxFileSystemProvider.readAttributes(LinuxFileSystemProvider.java:99)
	at java.base/java.nio.file.Files.readAttributes(Files.java:1763)
	at java.base/java.nio.file.Files.size(Files.java:2380)
	at io.helidon.media.common.PathBodyWriter$PathToChunks.map(PathBodyWriter.java:80)
	at io.helidon.media.common.PathBodyWriter$PathToChunks.map(PathBodyWriter.java:68)
	at io.helidon.common.mapper.Mapper.apply(Mapper.java:39)
	at io.helidon.common.reactive.SingleFlatMapMulti$FlatMapSubscriber.onNext(SingleFlatMapMulti.java:85)
	at io.helidon.common.reactive.SingleSubscription.request(SingleSubscription.java:50)
	at io.helidon.common.reactive.SingleFlatMapMulti$FlatMapSubscriber.onSubscribe(SingleFlatMapMulti.java:75)
	at io.helidon.common.reactive.SingleJust.subscribe(SingleJust.java:36)
	at io.helidon.common.reactive.SingleFlatMapMulti.subscribe(SingleFlatMapMulti.java:48)
	at io.helidon.media.common.MessageBodyContext$EventingPublisher.subscribe(MessageBodyContext.java:293)
	at io.helidon.webserver.Response.lambda$send$2(Response.java:206)
	at io.helidon.webserver.Response$SendLockSupport.execute(Response.java:375)
	at io.helidon.webserver.Response.send(Response.java:204)
	at io.helidon.webserver.Response.send(Response.java:238)
	at io.helidon.webserver.FileSystemContentHandler.send(FileSystemContentHandler.java:131)
	at io.helidon.webserver.ClassPathContentHandler.sendJar(ClassPathContentHandler.java:176)
	at io.helidon.webserver.ClassPathContentHandler.doHandle(ClassPathContentHandler.java:140)
	at io.helidon.webserver.StaticContentHandler.handle(StaticContentHandler.java:79)
	at io.helidon.webserver.StaticContentSupport.lambda$update$0(StaticContentSupport.java:64)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:320)
	at io.helidon.metrics.MetricsSupport$MetricsContextHandler.accept(MetricsSupport.java:619)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:320)
	at io.helidon.metrics.MetricsSupport.lambda$configureVendorMetrics$7(MetricsSupport.java:364)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:320)
	at io.helidon.openapi.OpenAPISupport.registerJsonpSupport(OpenAPISupport.java:164)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:320)
	at io.helidon.webserver.WebTracingConfig$RequestSpanHandler.accept(WebTracingConfig.java:247)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:320)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:87)
	at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:167)
```

## Environment Details
* Helidon Version: `2.0.2-SNAPSHOT`
* Helidon MP
* JDK version: `OpenJDK 64-Bit Server VM 18.9 (build 11.0.8+10-LTS, mixed mode, sharing)`
* OS: `Linux version 5.4.17-2011.4.4.el8uek.x86_64 (mockbuild@jenkins-10-147-72-125-c0965034-9ac1-44f0-bff6-98bec5b66adb) (gcc version 8.3.1 20190507 (Red Hat 8.3.1-4.5.0.8) (GCC)) #2 SMP Sat Jun 27 11:14:55 PDT 2020`

----------

## Problem Description
[//]: # "Describe the bug in detail highlighting current behavior vs expected behavior"
[//]: # "State if the problem is easily reproducible or happens intermittently"
[//]: # "Include stack traces or command outputs"

## Steps to reproduce
[//]: # "Step by step instructions to reproduce the problem"
[//]: # "Provide sample code/application if relevant"

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #2358
Signed-off-by: Daniel Kec <daniel.kec@oracle.com>

### CODE REVIEW

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java [hunk 1]
```diff
@@ -0,0 +1,131 @@
...
+        classPathContentHandler.sendJar(Http.Method.GET, FILE_NAME, jarUrl, request, response);
+        deleteTmpFiles();
+        classPathContentHandler.sendJar(Http.Method.GET, FILE_NAME, jarUrl, request, response);
+
+        assertThat(contents, containsInAnyOrder(FILE_CONTENT, FILE_CONTENT));
+    }
+
+    private void deleteTmpFiles() throws IOException {
+        File tempDir = File.createTempFile("tempLocator", "je").getParentFile();
+        LOGGER.info("Temp dir: " + tempDir.getAbsolutePath());
```
Comment (tomas-langer) [inline webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java:106]: Do not use `LOGGER.info` even in tests.

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java [hunk 2]
```diff
@@ -0,0 +1,131 @@
...
+
+        classPathContentHandler.sendJar(Http.Method.GET, FILE_NAME, jarUrl, request, response);
+        deleteTmpFiles();
+        classPathContentHandler.sendJar(Http.Method.GET, FILE_NAME, jarUrl, request, response);
+
+        assertThat(contents, containsInAnyOrder(FILE_CONTENT, FILE_CONTENT));
+    }
+
+    private void deleteTmpFiles() throws IOException {
+        File tempDir = File.createTempFile("tempLocator", "je").getParentFile();
```
Comment (tomas-langer) [inline webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java:105]: Use new I/O APIs (e.g. `Path` in this case)

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java [hunk 3]
```diff
@@ -0,0 +1,131 @@
...
+        LOGGER.info("Temp dir: " + tempDir.getAbsolutePath());
+        //Delete all temp files
+        for (File file : Objects.requireNonNull(tempDir.listFiles((dir, name) -> name.endsWith(".je")))) {
```
Comment (tomas-langer) [inline webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java:108]: This may be a big performance issue for the test if the temporary directory contains a lot of files.

**Review by tomas-langer — CHANGES_REQUESTED** [review]

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java (hunk 3 above)
Comment (tomas-langer) [reply webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java:108]: I think it would be best to allow an explicit folder to be configured for static content handler, and then send a new folder from this test as the configured value.
Then you can simply delete all files in that folder to simulate the cleanup

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java (hunk 1 above)
Comment (danielkec) [reply webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java]: fixed

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java (hunk 2 above)
Comment (danielkec) [reply webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java]: Fixed

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java (hunk 3 above)
Comment (danielkec) [reply webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java]: Great idea thx

File: microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java [hunk 4]
```diff
@@ -212,6 +212,9 @@ private void registerClasspathStaticContent(Config config) {
         cpBuilder.welcomeFileName(config.get("welcome")
                                           .asString()
                                           .orElse("index.html"));
+        config.get("tempFolder")
```
Comment (tomas-langer) [inline microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java:215]: As this is part of production code, the property name should follow convention.
Also directory is more commonly used.
So probably `tmp-dir` is the right configuration here

File: webserver/webserver/src/main/java/io/helidon/webserver/StaticContentSupport.java [hunk 5]
```diff
@@ -195,6 +196,17 @@ public Builder welcomeFileName(String welcomeFileName) {
             return this;
         }
 
+        /**
+         * Sets custom temporary folder for extracting static content from a jar.
+         *
+         * @param tempFolder custom temporary folder
+         * @return updated builder
+         */
+        public Builder tempFolder(Path tempFolder) {
```
Comment (tomas-langer) [inline webserver/webserver/src/main/java/io/helidon/webserver/StaticContentSupport.java:205]: please rename to `temporaryDirectory` or `tmpDir`. I think both `temp` and `folder` are less used

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java [hunk 6]
```diff
@@ -0,0 +1,142 @@
...
+import org.mockito.Mockito;
+
+public class UnstableTempTest {
+
+    private static final Logger LOGGER = Logger.getLogger(UnstableTempTest.class.getName());
+
+    private static final String JAR_NAME = "test.jar";
+    private static final String FILE_NAME = "test.js";
+    private static final String FILE_CONTENT = "alert(\"Hello, World!\");";
+    private static Path TEMP_DIR;
```
Comment (tomas-langer) [inline webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java:63]: Naming convention - this should be `tmpDir` or `tempDir` - all upper case is reserved for constants

**Review by tomas-langer — CHANGES_REQUESTED** [review]

File: microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java (hunk 4 above)
Comment (danielkec) [reply microprofile/server/src/main/java/io/helidon/microprofile/server/ServerCdiExtension.java]: fixed

File: webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java (hunk 6 above)
Comment (danielkec) [reply webserver/webserver/src/test/java/io/helidon/webserver/UnstableTempTest.java]: fixed

File: webserver/webserver/src/main/java/io/helidon/webserver/StaticContentSupport.java (hunk 5 above)
Comment (danielkec) [reply webserver/webserver/src/main/java/io/helidon/webserver/StaticContentSupport.java]: np

**Review by tomas-langer — APPROVED** [review]
LGTM
