### PR TITLE
Fix JSON conversion error during metrics formatting after idle period 1.x

### LINKED ISSUE #464: Request to endpoint /metrics fails occasionally
Requests to metrics path ```/metrics``` seems to fail from time to time and reports HTTP status 500. This occurs often when the Helidon application has been idle for a while.

## Environment Details
* Helidon Version: 1.0.0 & 2.2.0
* Helidon MP
* JDK version: 11 (build 11-28)
* OS: Linux
* Docker version: 18.09.02-CE

----------

## Problem Description
I'm using Prometheus (https://prometheus.io/) to gather metrics from various services (scrape configuration is to call ```/metrics``` endpoint twice per minute). Once or twice a day (often when the Helidon MP app has been idle for some time) the endpoint reports HTTP status 500 and an exception occurs which is caused by a NumberFormatException, see below screenshot. However, upcoming requests does work after a while.

helidon-metrics-stacktrace

## Steps to reproduce
Create a simple Helidon service and call ```/metrics``` on regular basic - after a few hours the endpoint reports HTTP status 500. Subsequent request will work but during the failure systems such as Prometheus will report that the service might be down which can cause negative alarms or other notifications.

## Addendum (reopening the issue)
The same general situation (long-running server -- unclear whether it has been idle or just long-running) gives the same symptom but during JSON formatting now.

### PR DESCRIPTION
**Pull request by tjquinno**
Resolves #464 for Helidon 1.x

See PR #2812 for full details.

Signed-off-by: tim.quinn@oracle.com <tim.quinn@oracle.com>

### CODE REVIEW

File: metrics2/metrics2/src/test/java/io/helidon/metrics/HelidonTimerTest.java [hunk 1]
```diff
@@ -1,5 +1,5 @@
 /*
- * Copyright (c) 2018, 2020 Oracle and/or its affiliates.
+ * Copyright (c) 2018,2021 Oracle and/or its affiliates.
```
Comment (tomas-langer) [inline metrics2/metrics2/src/test/java/io/helidon/metrics/HelidonTimerTest.java:2]: Please use spaces between comma and the second year.

Comment (tjquinno) [reply metrics2/metrics2/src/test/java/io/helidon/metrics/HelidonTimerTest.java:2]: Yeah, I know. I had to kick the pipeline to run the job again and was delayed in submitting the second, reverting commit. Sigh.

**Review by spericas — APPROVED** [review]
