### PR TITLE
Reactive streams compliant BareResponseImpl

### LINKED ISSUE #2496: BareResponseImpl throws ISE in Subscriber.onNext method
## Environment Details
* Helidon Version: 2.1.0

And spec rules [§ 2.13](https://github.com/reactive-streams/reactive-streams-jvm#2.13) and [§ 2.8](https://github.com/reactive-streams/reactive-streams-jvm#2.8) are violated.

```java
    @Override
    public void onNext(DataChunk data) {
        if (internallyClosed.get()) {
            throw new IllegalStateException("Response is already closed!");
        }
```

Expected behavior should be for BareResponseImpl to send cancel signal upstream and in case of subsequent onNext signal log a message about dropping DataChunk.

Current behavior causes problems for example with SSE, when multiple sse clients connect and one of them drops, ISE is thrown and app output get quickly polluted even in such legal situation.

## Reproducer 
```java
    SubmissionPublisher<String> broadCastPublisher = new SubmissionPublisher<>();

    void init(@Observes @Initialized(ApplicationScoped.class) Object o) {
        Multi.interval(300, TimeUnit.MILLISECONDS, Executors.newSingleThreadScheduledExecutor())
                .forEach(i -> broadCastPublisher.submit("message" + i));
    }

    @GET
    @Path("sse-reproduce")
    @Produces(MediaType.SERVER_SENT_EVENTS)
    public void listenToEvents(@Context Flow.Subscriber<String> sink) {
        broadCastPublisher.subscribe(sink);
    }
```
Curl endpoind, reveive few messages and then kill connection with Ctrl+C:
```sh
curl localhost:8080/example/sse-reproduce
data: message335
data: message336
data: message337
data: message338
data: message339
^C
```

```
2020.11.03 18:56:11 SEVERE org.glassfish.jersey.media.sse.internal.JerseyEventSink Thread[ForkJoinPool.commonPool-worker-13,5,main]: Processing onNext signal failed.
java.io.IOException: java.lang.IllegalStateException: java.lang.IllegalStateException: Response is already closed!
	at io.helidon.common.reactive.MultiFromOutputStream.doPublish(MultiFromOutputStream.java:180)
	at io.helidon.common.reactive.MultiFromOutputStream.publish(MultiFromOutputStream.java:158)
	at io.helidon.common.reactive.MultiFromOutputStream.write(MultiFromOutputStream.java:96)
	at io.helidon.webserver.jersey.ResponseWriter$1.write(ResponseWriter.java:52)
	at org.glassfish.jersey.message.internal.CommittingOutputStream.write(CommittingOutputStream.java:185)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$UnCloseableOutputStream.write(WriterInterceptorExecutor.java:271)
	at org.glassfish.jersey.media.sse.OutboundEventWriter$1.write(OutboundEventWriter.java:127)
	at java.base/java.io.OutputStream.write(OutputStream.java:157)
	at java.base/sun.nio.cs.StreamEncoder.writeBytes(StreamEncoder.java:242)
	at java.base/sun.nio.cs.StreamEncoder.implFlushBuffer(StreamEncoder.java:321)
	at java.base/sun.nio.cs.StreamEncoder.implFlush(StreamEncoder.java:325)
	at java.base/sun.nio.cs.StreamEncoder.flush(StreamEncoder.java:159)
	at java.base/java.io.OutputStreamWriter.flush(OutputStreamWriter.java:254)
	at org.glassfish.jersey.message.internal.ReaderWriter.writeToAsString(ReaderWriter.java:170)
	at org.glassfish.jersey.message.internal.AbstractMessageReaderWriterProvider.writeToAsString(AbstractMessageReaderWriterProvider.java:107)
	at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:76)
	at org.glassfish.jersey.message.internal.StringMessageProvider.writeTo(StringMessageProvider.java:36)
	at org.glassfish.jersey.media.sse.OutboundEventWriter.writeTo(OutboundEventWriter.java:113)
	at org.glassfish.jersey.media.sse.OutboundEventWriter.writeTo(OutboundEventWriter.java:43)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.invokeWriteTo(WriterInterceptorExecutor.java:242)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor$TerminalWriterInterceptor.aroundWriteTo(WriterInterceptorExecutor.java:227)
	at org.glassfish.jersey.message.internal.WriterInterceptorExecutor.proceed(WriterInterceptorExecutor.java:139)
	at org.glassfish.jersey.message.internal.MessageBodyFactory.writeTo(MessageBodyFactory.java:1116)
	at org.glassfish.jersey.server.ChunkedOutput$1.call(ChunkedOutput.java:231)
	at org.glassfish.jersey.server.ChunkedOutput$1.call(ChunkedOutput.java:198)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:292)
	at org.glassfish.jersey.internal.Errors.process(Errors.java:219)
	at org.glassfish.jersey.process.internal.RequestScope.runInScope(RequestScope.java:314)
	at org.glassfish.jersey.server.ChunkedOutput.flushQueue(ChunkedOutput.java:198)
	at org.glassfish.jersey.server.ChunkedOutput.write(ChunkedOutput.java:184)
	at org.glassfish.jersey.media.sse.internal.JerseyEventSink.onNext(JerseyEventSink.java:93)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consumeNext(SubmissionPublisher.java:1307)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.takeItems(SubmissionPublisher.java:1296)
	at java.base/java.util.concurrent.SubmissionPublisher$BufferedSubscription.consume(SubmissionPublisher.java:1253)
	at java.base/java.util.concurrent.SubmissionPublisher$ConsumerTask.exec(SubmissionPublisher.java:930)
	at java.base/java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:290)
	at java.base/java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1016)
	at java.base/java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1665)
	at java.base/java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1598)
	at java.base/java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:177)
Caused by: java.lang.IllegalStateException: java.lang.IllegalStateException: Response is already closed!
	at io.helidon.common.reactive.EmittingPublisher.internalEmit(EmittingPublisher.java:318)
	at io.helidon.common.reactive.EmittingPublisher$State$4.emit(EmittingPublisher.java:360)
	at io.helidon.common.reactive.EmittingPublisher.emit(EmittingPublisher.java:198)
	at io.helidon.common.reactive.MultiFromOutputStream.doPublish(MultiFromOutputStream.java:174)
	... 39 more
Caused by: java.lang.IllegalStateException: Response is already closed!
	at io.helidon.webserver.BareResponseImpl.onNext(BareResponseImpl.java:310)
	at io.helidon.webserver.BareResponseImpl.onNext(BareResponseImpl.java:56)
	at io.helidon.media.common.MessageBodyContext$EventingSubscriber.onNext(MessageBodyContext.java:334)
	at io.helidon.media.common.MessageBodyContext$EventingSubscriber.onNext(MessageBodyContext.java:300)
	at io.helidon.common.reactive.MultiMapperPublisher$MapperSubscriber.onNext(MultiMapperPublisher.java:80)
	at io.helidon.common.reactive.EmittingPublisher.internalEmit(EmittingPublisher.java:310)
	... 42 more
```

### PR DESCRIPTION
**Pull request by danielkec**
Fixes #2496

### CODE REVIEW

File: webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java [hunk 1]
```diff
@@ -221,6 +222,7 @@ private void completeResponseFuture(Throwable throwable) {
             responseFuture.complete(this);
         } else {
             LOGGER.finer(() -> log("Response completion failed %s", throwable));
+            Optional.ofNullable(subscription).ifPresent(Flow.Subscription::cancel);
```
Comment (romain-grecourt) [inline webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java:225]: The use of optional feels overkill here ;)
Why not just `if (subscripton != null) subscription.cancel()`

Comment (danielkec) [reply webserver/webserver/src/main/java/io/helidon/webserver/BareResponseImpl.java]: Hah thx fixed

**Review by romain-grecourt — APPROVED** [review]
LGTM, how much local testing have you done ?
