### PR TITLE
Fix injection of metrics registry in native image

### LINKED ISSUE #2892: Unable to inject MetricRegistry when using Graal native-image
## Environment Details
* Helidon Version: 2.2.1
* Helidon SE or Helidon MP: MP
* JDK version: Graal 21.0.0 native-image
* OS: scratch
* Docker version (if applicable): Docker for Desktop Windows 3.2.2

----------

## Problem Description
Unable to inject any of the `org.eclipse.microprofile.metrics.MetricRegistry` instances resulting in:

```
Exception in thread "main" org.jboss.weld.exceptions.IllegalArgumentException: WELD-001456: Argument resolvedBean 
must not be null
        at org.jboss.weld.util.Preconditions.checkArgumentNotNull(Preconditions.java:40)
        at org.jboss.weld.manager.BeanManagerImpl.getInjectableReference(BeanManagerImpl.java:746)
        at org.jboss.weld.injection.FieldInjectionPoint.inject(FieldInjectionPoint.java:92)
        at org.jboss.weld.util.Beans.injectBoundFields(Beans.java:336)
        at org.jboss.weld.util.Beans.injectFieldsAndInitializers(Beans.java:347)
        at org.jboss.weld.injection.producer.ResourceInjector$1.proceed(ResourceInjector.java:69)
        at org.jboss.weld.injection.InjectionContextImpl.run(InjectionContextImpl.java:48)
        at org.jboss.weld.injection.producer.ResourceInjector.inject(ResourceInjector.java:71)
        at org.jboss.weld.injection.producer.BasicInjectionTarget.inject(BasicInjectionTarget.java:117)
        at org.jboss.weld.bean.ManagedBean.create(ManagedBean.java:161)
        at org.jboss.weld.contexts.AbstractContext.get(AbstractContext.java:96)
        at org.jboss.weld.bean.ContextualInstanceStrategy$DefaultContextualInstanceStrategy.get(ContextualInstanceStrategy.java:100)
        at org.jboss.weld.bean.ContextualInstanceStrategy$ApplicationScopedContextualInstanceStrategy.get(ContextualInstanceStrategy.java:140)
        at org.jboss.weld.bean.ContextualInstance.get(ContextualInstance.java:67)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiver(ObserverMethodImpl.java:360)
        at org.jboss.weld.event.ObserverMethodImpl.getReceiverIfExists(ObserverMethodImpl.java:347)
        at org.jboss.weld.event.ObserverMethodImpl.sendEvent(ObserverMethodImpl.java:305)
        at org.jboss.weld.event.ObserverMethodImpl.notify(ObserverMethodImpl.java:286)
        at javax.enterprise.inject.spi.ObserverMethod.notify(ObserverMethod.java:124)
        at org.jboss.weld.util.Observers.notify(Observers.java:166)
        at org.jboss.weld.event.ObserverNotifier.notifySyncObservers(ObserverNotifier.java:285)
        at org.jboss.weld.event.ObserverNotifier.notify(ObserverNotifier.java:273)
        at org.jboss.weld.event.EventImpl.fire(EventImpl.java:96)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.doStart(HelidonContainerImpl.java:339)
        at io.helidon.common.context.Contexts.runInContext(Contexts.java:137)
        at io.helidon.microprofile.cdi.HelidonContainerImpl.start(HelidonContainerImpl.java:249)
        at io.helidon.microprofile.cdi.Main.main(Main.java:80)
```

## Steps to reproduce
1. Use Helidon MP Quickstart,
2. Inject a `MetricRegistry` (any Type) 

## Workaround
Add the following into `reflect-config.json`:
```json
[
  {
    "name":"io.helidon.microprofile.metrics.RegistryProducer",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allPublicMethods":true,
    "allDeclaredConstructors":true
  },{
    "name":"org.eclipse.microprofile.metrics.MetricRegistry",
    "allDeclaredMethods":true,
    "methods":[{"name":"<init>","parameterTypes":[] }]
  },{
    "name":"org.eclipse.microprofile.metrics.annotation.RegistryType",
    "allDeclaredFields":true,
    "allDeclaredMethods":true,
    "allDeclaredConstructors":true
  }
]
```
Not sure if all of them are needed, but it got it working.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #2892 

Separated into meaningful commits:
- Update to Helidon reflection feature to reduce issues when registering for reflection in native image (ignore classes with fields or type parameters that are not on classpath)
- Fix a regression in Jersey integration that caused failures in native image build
- Reduce warnings by adding "initialize at runtime" for a few Netty classes
- Fix of the related bug
- Squashable (copyright fix)

### CODE REVIEW

File: integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java [hunk 1]
```diff
@@ -742,10 +753,22 @@ boolean isExcluded(Class<?> theClass) {
 
         private final Class<?> clazz;
 
+        private boolean validated;
+        private boolean valid = true;
```
Comment (cuspymd) [inline integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java:757]: How are the two variables different?

Comment (tomas-langer) [reply integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java:757]: `validated` marks whether we touched this file
`valid` means it is valid (if `validated` is true as well)
This is to make sure the validation happens before we start registering the class

Comment (tomas-langer) [reply integrations/graal/native-image-extension/src/main/java/io/helidon/integrations/graal/nativeimage/extension/HelidonReflectionFeature.java:757]: `validated` marks whether we touched this file
`valid` means it is valid (if `validated` is true as well)
This is to make sure the validation happens before we start registering the class

**Review by danielkec — APPROVED** [review]
