### PR TITLE
2.0: Fix #1711 StaticContentHandler fails with encoded URLs

### LINKED ISSUE #1711: StaticContentHandler fails with encoded URLs
## Environment Details
* Helidon Version: 2.0.0-SNAPSHOT
----------

## Problem Description
When an encoded URL is processed by `ClassPathContentHandler` it fails with an `IllegalArgumentException` and generates a 500 server error. This is a regression and breaks examples/microprofile/messaging-sse

Also, the exception is logged at the FINE level. Anything that generates a 500 should log the error at the ERROR level.

Here is the exception:
```
[Fri May 01 10:34:47 PDT 2020] FINEST: io.helidon.webserver.RequestRouting$RoutedRequest next - (reqID: 3) Routing next: /example/send/Fly Helidon!
[Fri May 01 10:34:47 PDT 2020] FINEST: io.helidon.webserver.ClassPathContentHandler doHandle - Requested class path resource: WEB/example/send/Fly Helidon!
[Fri May 01 10:34:47 PDT 2020] FINE: io.helidon.webserver.StaticContentHandler handle - Failed to access static resource
java.lang.IllegalArgumentException: Illegal character in path at index 20: WEB/example/send/Fly Helidon!
	at java.base/java.net.URI.create(URI.java:883)
	at io.helidon.webserver.ClassPathContentHandler.doHandle(ClassPathContentHandler.java:95)
	at io.helidon.webserver.StaticContentHandler.handle(StaticContentHandler.java:79)
	at io.helidon.webserver.StaticContentSupport.lambda$update$0(StaticContentSupport.java:64)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.media.jsonp.server.JsonSupport.accept(JsonSupport.java:98)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.media.jsonp.server.JsonSupport.accept(JsonSupport.java:98)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.metrics.MetricsSupport$MetricsContextHandler.accept(MetricsSupport.java:621)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.metrics.MetricsSupport.lambda$configureVendorMetrics$7(MetricsSupport.java:372)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.webserver.WebTracingConfig$RequestSpanHandler.accept(WebTracingConfig.java:234)
	at io.helidon.webserver.RequestRouting$RoutedRequest.next(RequestRouting.java:317)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:98)
	at io.helidon.webserver.RequestRouting.route(RequestRouting.java:82)
	at io.helidon.webserver.ForwardingHandler.channelRead0(ForwardingHandler.java:153)
	at io.netty.channel.SimpleChannelInboundHandler.channelRead(SimpleChannelInboundHandler.java:99)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.handler.codec.ByteToMessageDecoder.fireChannelRead(ByteToMessageDecoder.java:321)
	at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:295)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:355)
	at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:377)
	at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:363)
	at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919)
	at io.netty.channel.nio.AbstractNioByteChannel$NioByteUnsafe.read(AbstractNioByteChannel.java:163)
	at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:714)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:650)
	at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:576)
	at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:493)
	at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:989)
	at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74)
	at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30)
	at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: java.net.URISyntaxException: Illegal character in path at index 20: WEB/example/send/Fly Helidon!
	at java.base/java.net.URI$Parser.fail(URI.java:2915)
	at java.base/java.net.URI$Parser.checkChars(URI.java:3086)
	at java.base/java.net.URI$Parser.parseHierarchical(URI.java:3168)
	at java.base/java.net.URI$Parser.parse(URI.java:3127)
	at java.base/java.net.URI.<init>(URI.java:600)
	at java.base/java.net.URI.create(URI.java:881)
	... 39 more

[Fri May 01 10:34:47 PDT 2020] FINEST: io.helidon.webserver.RequestRouting$RoutedRequest nextNoCheck - (reqID: 3) Routing error: class io.helidon.webserver.HttpException
[Fri May 01 10:34:47 PDT 2020] FINEST: io.helidon.webserver.BareResponseImpl writeStatusAndHeaders - (reqID: 3) Writing headers: 500 Internal Server Error
```

## Steps to reproduce
1. Go to `examples/microprofile/messaging-sse` and change logging.properties so that `.level=FINEST`
2. Build and run `examples/microprofile/messaging-sse`
3. Load page in browser and click Send (which by defaults sends text with spaces that must be URL encoded).
4. See error from server

### PR DESCRIPTION
**Pull request by barchetta**

### CODE REVIEW

File: webserver/webserver/src/main/java/io/helidon/webserver/ClassPathContentHandler.java [hunk 1]
```diff
@@ -92,7 +92,9 @@ boolean doHandle(Http.RequestMethod method, String requestedPath, ServerRequest
         LOGGER.finest(() -> "Requested class path resource: " + resource);
 
         // this MUST be done, so we do not escape the bounds of configured directory
-        String requestedResource = URI.create(resource).normalize().toString();
+        // We use multi-arg constructor so it performs url encoding
+        URI myuri = new URI(null, null, resource, null);
```
Comment (romain-grecourt) [inline webserver/webserver/src/main/java/io/helidon/webserver/ClassPathContentHandler.java:96]: You don't need the intermediate variable right ? It can just be `new URI(null, null, resource, null).normalize().getPath()`

Comment (barchetta) [reply webserver/webserver/src/main/java/io/helidon/webserver/ClassPathContentHandler.java:96]: I find this way more readable  with multi-arg constructor. Easier to step through with a debugger. If exception is thrown you know the method it came from. Compiler will optimize it for me.

File: webserver/webserver/src/test/java/io/helidon/webserver/StaticContentHandlerTest.java [hunk 2]
```diff
@@ -218,6 +219,17 @@ public void handleNextOnFalse() throws Exception {
         assertThat(handler.counter.get(), is(1));
     }
 
+    @Test
+    public void cpHandleSpaces() throws Exception {
```
Comment (ljnelson) [inline webserver/webserver/src/test/java/io/helidon/webserver/StaticContentHandlerTest.java:223]: Nit? maybe? I don't understand what `cp` is short for here.
