### PR TITLE
Restart support for CDI regardless of mode used.

### LINKED ISSUE #1554: CDI restart cause issues
When we start CDI using one approach, shut it down and start again using a different approach, we get an exception.

The following:
```
        SeContainer container = SeContainerInitializer.newInstance()
                .disableDiscovery()
                .addBeanClasses(BmProducers.class)
                .initialize();

        container.close();

        Server.create().start();
```
causes
```
Exception in thread "main" java.lang.IllegalStateException: Unable to access CDI
	at javax.enterprise.inject.spi.CDI.lambda$getCDIProvider$1(CDI.java:88)
	at java.base/java.util.Optional.orElseThrow(Optional.java:408)
	at javax.enterprise.inject.spi.CDI.getCDIProvider(CDI.java:88)
	at javax.enterprise.inject.spi.CDI.current(CDI.java:64)
	at io.helidon.microprofile.server.Server$Builder.doBuild(Server.java:203)
	at io.helidon.common.context.Contexts.runInContext(Contexts.java:118)
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:188)
	at io.helidon.microprofile.server.Server.create(Server.java:81)
```

The following:
```
SeContainer container = SeContainerInitializer.newInstance()
                .disableDiscovery()
                .addBeanClasses(BmProducers.class)
                .initialize();

        ((SeContainer)CDI.current()).close();


        Server.create().start();
```

Causes
```
Exception in thread "main" java.lang.NullPointerException
	at io.helidon.microprofile.server.Server$Builder.build(Server.java:166)
	at io.helidon.microprofile.server.Server.create(Server.java:81)
```

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>
Resolves #1554

### CODE REVIEW

File: microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ContainerInstanceHolder.java [hunk 1]
```diff
@@ -38,7 +39,12 @@ static void set(HelidonContainer container) {
         CONTAINER.set(container);
     }
 
-    static HelidonContainer get() {
+    // return true if the container was reset, indicating somebody started CDI by hand and then shut it down
+    static synchronized boolean isReset() {
+        return isReset;
+    }
```
Comment (danielkec) [inline microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ContainerInstanceHolder.java:45]: Is synchronized needed here?

File: microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/Main.java [hunk 2]
```diff
@@ -58,13 +60,21 @@ private Main() {
...
-        CONTAINER.start();
+        if (ContainerInstanceHolder.isReset()) {
+            // in case somebody restarted the container, we need to get a new one
+            inUse = ContainerInstanceHolder.get();
+        } else {
+            // use the statically initialized one
+            inUse = CONTAINER;
+        }
+
+        inUse.start();
```
Comment (danielkec) [inline microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/Main.java:71]: I don't see the whole picture, but can someone call `reset()` on container holder between the `isReset()` check and `start()`?

Comment (tomas-langer) [reply microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/Main.java:71]: No. You cannot run two containers in parallel. You can run them sequentially. And this is to make sure that if you run a container, shut it down and then run the `Main` class, everything works fine (the `CONTAINER` field is there for `native-image` static initialization)

File: microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ContainerInstanceHolder.java (hunk 1 above)
Comment (tomas-langer) [reply microprofile/cdi/src/main/java/io/helidon/microprofile/cdi/ContainerInstanceHolder.java:45]: Yes, as the field is not atomic. Either you must use `synchronized` from all places that use the field, have it declared `volatile` or use `AtomicBoolean`. As I already used `synchronized` in the other methods and this class is used once during startup and once during shutdown, the overhead is negligible
