### PR TITLE
Fix #111 Prometheus fails to scrape Helidon metrics

### LINKED ISSUE #111: Prometheus fails to scrape Helidon metrics
## Environment Details
* Helidon Version: 0.10.1
* Helidon SE
* JDK version: 1.8.0_162
* OS: MacOS
----------

## Problem Description
Prometheus 2.2.1 and 2.4.3 fail to scrape Helidon metrics. Prometheus reports the error `no token found`. This error is typically reported by Prometheus when it can't parse the scrapped metrics data.

## Steps to reproduce
1. Build and run this Helidon app: https://github.com/barchetta/helidon-se-codeone-2018
2. Download and run Prometheus 2.2.1 (https://github.com/prometheus/prometheus/releases/tag/v2.2.1)
3. Add a scrape_configs to prometheus.yml like this:
```
  - job_name: 'helidon'

    metrics_path: '/metrics/'
    # metrics_path defaults to '/metrics'
    # scheme defaults to 'http'.

    static_configs:
      - targets: ['localhost:8080']
```

You'll see prometheus report:
```
level=warn ts=2018-10-16T01:35:44.714172501Z caller=scrape.go:697 component="scrape manager" scrape_pool=helidon target=http://localhost:8080/metrics/ msg="append failed" err="no token found"
```

### PR DESCRIPTION
**Pull request by barchetta**
Also added a test to verify we determine the correct metrics output type based on various Accept headers. This required adding a helper class to WebServer to allow construction of RequestHeaders by the metrics test.

### CODE REVIEW

File: microprofile/metrics/metrics-se/src/main/java/io/helidon/metrics/MetricsSupport.java [hunk 1]
```diff
@@ -138,14 +143,32 @@ public static Builder builder() {
...
 
+    /**
+     * Check if the passed headers (specifically Accept) prefer
+     * data in JSON format.
+     *
+     * @return true if passed headers prefer data in JSON format.
+     */
+    static boolean requestsJsonData(RequestHeaders headers) {
+        Optional<MediaType> mediaType = headers.bestAccepted(MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN);
+        boolean requestsJson =  mediaType.isPresent() && mediaType.get().equals(MediaType.APPLICATION_JSON);
```
Comment (romain-grecourt) [inline microprofile/metrics/metrics-se/src/main/java/io/helidon/metrics/MetricsSupport.java]:
```suggestion
       boolean requestsJson = headers.bestAccepted(MediaType.APPLICATION_JSON, MediaType.TEXT_PLAIN)
                .map((mt) -> MediaType.APPLICATION_JSON.equals(mt))
                .orElse(Boolean.FALSE);
```

File: microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java [hunk 2]
```diff
@@ -0,0 +1,98 @@
...
+    @Test
+    void testTextPlainAccept() {
+        RequestHeaders hs = constructRequestHeaders(Http.Header.ACCEPT, "text/plain");
+        assertFalse(MetricsSupport.requestsJsonData(hs));
+    }
+
+    @Test
+    void testTextPlain2Accept() {
+        RequestHeaders hs = constructRequestHeaders(Http.Header.ACCEPT, "text/plain;q=1,application/json;q=.5");
+        assertFalse(MetricsSupport.requestsJsonData(hs));
```
Comment (tomas-langer) [inline microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java]: This is not according to MP Metrics spec (at least according to my understanding):
_Prometheus text format - default response format when the HTTP Accept header does not match
any more specific media type like application/json._
As in this case the accept header DOES match a more specific format, this should return JSON and not text.

File: microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java [hunk 3]
```diff
@@ -0,0 +1,98 @@
...
+    private RequestHeaders constructRequestHeaders(String name, String... values) {
+        Map<String, List<String>> map = new HashMap<>(1);
+        map.put(name, new ArrayList<>(Arrays.asList(values)));
+        return WebServerHelper.constructRequestHeaders(map);
+    }
+
+    @Test
+    void testPrometheusAccept() {
+        RequestHeaders hs = constructRequestHeaders(Http.Header.ACCEPT, "text/plain;version=0.0.4;q=1,*/*;q=0.1");
+        assertFalse(MetricsSupport.requestsJsonData(hs));
```
Comment (tomas-langer) [inline microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java]: This is not according to MP Metrics spec (at least according to my understanding):
Prometheus text format - default response format when the HTTP Accept header does not match
any more specific media type like application/json.
As in this case the accept header DOES match a more specific format, this should return JSON and not text.

File: webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java [hunk 4]
```diff
@@ -0,0 +1,44 @@
...
+    /**
+     * Create an instance of RequestHeaders.
+     *
+     * @param headerMap a Map of request headers
+     *
+     * @return a new instance built with the passed headers
+     */
+    public static RequestHeaders constructRequestHeaders(Map<String, List<String>> headerMap) {
+        return new HashRequestHeaders(headerMap);
+    }
```
Comment (tomas-langer) [inline webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java]: Adding a new class to public API of Helidon seems like a bit of an overkill for a single method. Also I do not like the idea of test support being part of core packages.
Also you can use mocking for testing.

File: microprofile/metrics/metrics-se/src/main/java/io/helidon/metrics/MetricsSupport.java (hunk 1 above)
Comment (barchetta) [reply microprofile/metrics/metrics-se/src/main/java/io/helidon/metrics/MetricsSupport.java]: Bike shedding.

File: microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java (hunk 2 above)
Comment (barchetta) [reply microprofile/metrics/metrics-se/src/test/java/io/helidon/metrics/AcceptHeaderTest.java]: That section of the spec is vague. I claim it is better to interpret it in a way that makes sense and is consistent with the HTTP protocol and works with Prometheus. We have to work with Prometheus.

File: webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java (hunk 4 above)
Comment (barchetta) [reply webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java]: I understand not wanting to add this to the public API and I'm open to other suggestions. But I don't like mocking RequestHeaders because the fix is sensitive to WebServer's behavior of RequestHeaders. And I'd be testing the mock more than the fix. 

So maybe this is not well suited for a unit test.

Comment (spericas) [reply webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java]: Method `requestsJsonData` adds very little logic on top of `bestAccepted`. Wouldn't it be sufficient to test the use case in the `webserver` module and simply this?

Comment (barchetta) [reply webserver/webserver/src/main/java/io/helidon/webserver/WebServerHelper.java]: And I had a bug in that "very little logic" when I first wrote the method. I really want to test the code path for determining if we generate Prometheus or JSON format. At this point I'm thinking this is best left to a functional or integration type test instead of a unit test. I'll remove this unit test.

**Comment by tomas-langer** [comment]
The explanation from MP Metrics is clear and this should fix it. Thanks!
