### PR TITLE
MetricSupport and RegistryFactory can be accessed in any order now.

### LINKED ISSUE #360: MetricsSupport must be created before a service accesses the registry
## Environment Details
* Helidon Version: 0.11.0
* Helidon SE
* JDK version: 9.0.4
* OS: Mac OS High Sierra
* Docker version (if applicable): n/a

----------

## Problem Description
The developer must invoke `MetricsSupport.create` before a metrics-enabled service tries to access the metrics registry or an NPE results.

## Steps to reproduce
In the SE restful web service guide code (helidon/examples/guides/se-restful-webservice) find the `Main.createRouting` method. As written, it first creates the `MetricsSupport` object and then instantiates `GreetService`. Reverse the order. Then try to `mvn package` the project. The test will fail with an NPE. Restore the original order and the test passes.

Ideally, this ordering would not be important. This issue is for investigating whether there is a way to remove the ordering requirement.

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

Resolves #360

### CODE REVIEW

File: metrics/metrics/src/main/java/io/helidon/metrics/RegistryFactory.java [hunk 1]
```diff
@@ -74,20 +80,61 @@ static RegistryFactory create() {
      * @return supplier of registry factory (to bind as late as possible)
      */
     public static Supplier<RegistryFactory> getRegistryFactory() {
-        return () -> staticInstance;
+        return () -> {
```
Comment (tjquinno) [inline metrics/metrics/src/main/java/io/helidon/metrics/RegistryFactory.java]: Could this simply invoke `getInstance()` for the caller, rather than throw an exception? 

Doing so might mask the case where the developer intended to use config but forgot to. But if the developer had invoked `getInstance()` explicitly instead of `getInstance(Config)` s/he would have to diagnose the same sort of problem.

Comment (tomas-langer) [reply metrics/metrics/src/main/java/io/helidon/metrics/RegistryFactory.java]: Refactored a bit more - now we mostly use a singleton instance, with support for customized RegistryFactory (and MetricSupport) - if for any reason somebody wants more than one RegistryFactory in their application accessible on different endpoints

**Comment by tomas-langer** [comment]
Additional commit fixing spotbugs issue (changes in singleton made a few null checks obsolete.
