### PR TITLE
Fail fast when policy validation fails because of setup/syntax.

### LINKED ISSUE #1487: EL Policy statement parsing failure does not fail setup
When the EL Policy statement contains an invalid expression, such as backtick instead of single quote in `${inRole(user, 'admin')}`, the parsing fails, but is only represented as a `403` response code, instead of a proper parsing expression that fails the application.

### PR DESCRIPTION
**Pull request by tomas-langer**
Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

Resolves #1487 for 2.x

### CODE REVIEW

File: security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java [hunk 1]
```diff
@@ -164,9 +161,8 @@ public JavaxElPolicyExecutor build() {
                 try {
                     expressionFactory = ExpressionFactory.newInstance();
                 } catch (ELException e) {
-                    LOGGER.fine(
-                            "Expression language factory not available. To support policy expressions, you need to add some "
-                                    + "implementation to class/module path");
+                    throw new SecurityException("Failed to configure ABAC Policy support for Jakarta Expression Language,"
```
Comment (ljnelson) [inline security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java]: Consider wrapping `e` so it isn't lost.

Comment (tomas-langer) [reply security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java]: Good catch, will fix

Comment (tomas-langer) [reply security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java]: Fixed.

File: security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java [hunk 2]
```diff
@@ -116,11 +116,8 @@ public void executePolicy(String policyStatement, Errors.Collector collector, Pr
                 collector.fatal(this, "Policy statement \"" + policyStatement + "\" evaluated to false");
             }
         } catch (Exception e) {
-            collector.fatal(this,
-                            "Policy statement \"" + policyStatement + "\" evaluated to an exception " + e.getClass()
-                                    .getName() + " with message: " + e.getMessage());
-
             LOGGER.log(Level.FINEST, e, () -> "Statement " + policyStatement + " evaluation failed");
+            throw new SecurityException("Policy statement \"" + policyStatement + "\" evaluated to an exception", e);
```
Comment (danielkec) [inline security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java]: Is logging still needed here?

Comment (tomas-langer) [reply security/abac/policy-el/src/main/java/io/helidon/security/abac/policy/el/JavaxElPolicyExecutor.java]: The security exception is propagated outside of security (and outside of Helidon code), so yes, I think it is reasonable to log it (that is why it is in `FINEST` level)
