### PR TITLE
Fixed interfering tests in MP config.

### LINKED ISSUE #2647: ObjectMappingTest in microprofile/config can affect other unit tests' data
This is mostly a tracking bug mainly so it doesn't get lost.

While investigating a user's report about environment variable overrides, I wrote a simple unit test in `microprofile/config`.  When this unit test is run and `ObjectMappingTest` is also run, my test's environment does not contain what it should.  When I exclude `ObjectMappingTest` from the test run but include all others, its environment does contain what it should.

My first uninformed guess is that something in registering `Config` instances in our `ConfigProviderResolver` is not fully resetting state.  But that is a guess.

The easy workaround to this issue is almost certainly going to be to set Surefire's `reuseForks` to `false`.

### PR DESCRIPTION
**Pull request by tomas-langer**
Resolves #2647 

 - The method `releaseConfig` did not correctly take into account usage of `ConfigDelegate`.
 - reset the reuseForks back to default
 - META-INF/services for YAML config source is not needed, it is part of the library
 - The `ObjectMappingTest` did not correctly handle release of configuration.
 - Removed extensive `final` declarations in test

Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

### CODE REVIEW

**Review by ljnelson — APPROVED** [review]

File: config/config-mp/src/main/java/io/helidon/config/mp/MpConfigProviderResolver.java [hunk 1]
```diff
@@ -173,13 +173,23 @@ public void releaseConfig(Config config) {
...
+                        break;
+                    }
+                }
+            } else {
+                for (Map.Entry<ClassLoader, ConfigDelegate> entry : CONFIGS.entrySet()) {
+                    Config configFromRef = entry.getValue().delegate();
+                    if (config == configFromRef) {
+                        cl.set(entry.getKey());
+                        break;
+                    }
```
Comment (danielkec) [inline config/config-mp/src/main/java/io/helidon/config/mp/MpConfigProviderResolver.java:192]: Maybe something like this could avoid code duplication
```java
Predicate<Map.Entry<ClassLoader, ConfigDelegate>> entryPredicate;

if(config instanceof ConfigDelegate){
    entryPredicate = entry -> config == entry.getValue();
}else {
    entryPredicate = entry -> config == entry.getValue().delegate();
}

CONFIGS.entrySet()
        .stream()
        .filter(entryPredicate)
        .findFirst()
        .map(Map.Entry::getKey)
        .ifPresent(cl::set);
```

Comment (danielkec) [reply config/config-mp/src/main/java/io/helidon/config/mp/MpConfigProviderResolver.java:192]: On the other hand it's not shorter nor more readable and definitely not faster

**Review by danielkec — APPROVED** [review]
