### PR TITLE
Fail deployment for Gauges in RequestScoped beans

### LINKED ISSUE #1977: @Gauge in ReqeustScope breaks all metrics
Following the example from [TomiTribe](https://www.tomitribe.com/blog/getting-started-with-microprofile-metrics/#:~:text=The%20MicroProfile%20Metrics%20is%20a,build%20their%20own%20application%20metrics.) we have:

```
@Path("gauge")
@RequestScoped
public class GaugeReproducer {
    @GET
    @Path("/price")
    public Response getItemsPrice() {
        return Response.ok(getPrice()).build();
    }

    @Gauge(unit = "Heads", name = "addHeadGauge", absolute = true)
    public long getPrice() {
        return 4;
    }
}
```
And the request works fine:
```
    public static void main(String[] args) {
        try (Response response = ClientBuilder.newClient()
                .target("http://localhost:8080").path("gauge/price")
                .request(MediaType.APPLICATION_JSON_TYPE).get()) {
            Assertions.assertEquals(200, response.getStatus());
        }
    }
```
But when we made a request to metrics url _http://localhost:8080/metrics/application_ we get a response:
> java.lang.reflect.InvocationTargetException

And the server log contains the full stack trace:
> 2020.06.11 11:17:41 WARNING io.helidon.webserver.RequestRouting Thread[nioEventLoopGroup-3-3,10,main]: Default error handler: Unhandled exception encountered.
java.util.concurrent.ExecutionException: Unhandled 'cause' of this exception encountered.
	at io.helidon.webserver.RequestRouting$RoutedRequest.defaultHandler(RequestRouting.java:387)
	at io.helidon.webserver.RequestRouting$RoutedRequest.nextNoCheck(RequestRouting.java:367)
...
Caused by: java.lang.RuntimeException: java.lang.reflect.InvocationTargetException
	at io.helidon.microprofile.metrics.DelegatingGauge.getValue(DelegatingGauge.java:66)
	at io.helidon.metrics.HelidonGauge.getValue(HelidonGauge.java:57)
...
Caused by: java.lang.reflect.InvocationTargetException
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.base/java.lang.reflect.Method.invoke(Method.java:566)
	at io.helidon.microprofile.metrics.DelegatingGauge.getValue(DelegatingGauge.java:64)
...
Caused by: org.jboss.weld.contexts.ContextNotActiveException: WELD-001303: No active contexts for scope type javax.enterprise.context.RequestScoped
	at org.jboss.weld.manager.BeanManagerImpl.getContext(BeanManagerImpl.java:647)

### PR DESCRIPTION
**Pull request by tomas-langer**
Warn for Gauges not in ApplicationScoped or Singleton beans

Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

Resolves #1977

### CODE REVIEW

File: microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java [hunk 1]
```diff
@@ -449,6 +462,21 @@ private void recordAnnotatedGaugeSite(@Observes @WithAnnotations(Gauge.class) Pr
             return;
         }
 
+        Annotation annotation = type.getAnnotation(RequestScoped.class);
+        if (annotation != null) {
+            errors.fatal(clazz, "Cannot configure @Gauge on a request scoped bean");
```
Comment (tjquinno) [inline microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java:467]: Is failing preferable to warning in this case?

Comment (tomas-langer) [reply microprofile/metrics/src/main/java/io/helidon/microprofile/metrics/MetricsCdiExtension.java:467]: See: https://github.com/eclipse/microprofile-metrics/pull/367/files

In general disabling a feature means it works differently from what user wanted - in this case it cannot work and the annotation is wrong, so I think an exception is the right way to process it.

**Comment by tomas-langer** [comment]
Related spec PR:
https://github.com/eclipse/microprofile-metrics/pull/367
