### PR TITLE
Fix NPE in outbound of JWT provider.

### LINKED ISSUE #3246: JWT fails when calling outbound using JAX-RS client
When JWT provider is configured (using JWK to verify inbound JWT), and a call is done using JAX-RS client, a NPE is throw from `JwtProvider` line 283 (version 2.3.0).

This can be fixed by denying propagation explicitly using `propagate:false` in `jwt` provider configuration.

### PR DESCRIPTION
**Pull request by tomas-langer**
Added tests to verify.

Resolves #3246 

Signed-off-by: Tomas Langer <tomas.langer@oracle.com>

### CODE REVIEW

File: security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java [hunk 1]
```diff
@@ -603,7 +604,7 @@ public Builder validitySeconds(long validitySeconds) {
                 .tokenHeader("Authorization")
                 .tokenPrefix("bearer ")
                 .build();
-        private OutboundConfig outboundConfig;
+        private OutboundConfig outboundConfig = OutboundConfig.builder().build();
```
Comment (danielkec) [inline security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java:607]: Other defaults are defined in the builder, wouldn't it be a better place for this one? 
https://github.com/oracle/helidon/blob/ce28e044a5e13428a6d16f946b2fe10709fd6ed4/security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java#L594-L611

Comment (danielkec) [reply security/providers/jwt/src/main/java/io/helidon/security/providers/jwt/JwtProvider.java:607]: It is, sorry my bad

**Review by danielkec — APPROVED** [review]
